dependencies = [
    "google-generativeai>=0.8.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.40",
    "streamlit-extras>=0.6.0",
    "streamlit>=1.44.1",
]
